repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.2.0
    hooks:
      # File validity checkers
      - id: check-yaml
      - id: check-toml
      # Fix whitespace at end of lines and ensures single line ends file
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # Cleanliness, ensure files do not have UTF marker and no
      - id: fix-byte-order-marker
      - id: mixed-line-ending

  # "Darker" runs the black formatter, isort import sorter, and
  # flake8 checker only on edited lines rather than entire file
  - repo: 'https://github.com/akaihola/darker'
    rev: 1.5.0
    hooks:
      - id: darker
        args:
          # - '--isort'
          - '-L'
          - flake8
        additional_dependencies:
          # - isort
          - flake8
          - flake8-bugbear
          - pep8-naming


  - repo: 'https://github.com/jlebar/pre-commit-hooks.git'
    rev: 62ca83ba4958da48ea44d9f24cd0aa58633376c7
    hooks:
      - id: clang-format-diff
        verbose: true
        types_or: [c++, c]



  # Allow black to be run on entire file manually
  # Use pre-commit run --hook-stage manual black
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [manual]

  # Allow isort to be run on entire file manually
  # Use pre-commit run --hook-stage manual isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
        - id: isort
          stages: [manual]

  # Allow flake8 to be run on entire file manually
  # Use pre-commit run --hook-stage manual flake8
  - repo: 'https://github.com/pycqa/flake8'
    rev: 4.0.1
    hooks:
      - id: flake8
        stages: [manual]
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming

  # Allow clang-format to be run on entire file manually
  # Use pre-commit run --hook-stage manual clang-format-whole-file
  - repo: 'https://github.com/jlebar/pre-commit-hooks.git'
    rev: 62ca83ba4958da48ea44d9f24cd0aa58633376c7
    hooks:
      - id: clang-format-whole-file
        stages: [manual]
        verbose: true
        types_or: [c++, c]
