# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.7
matrix:
  include:
    - python: 3.3
      env: USE_CHROOT=1 ARCH=i386 DIST=trusty PYTHON=3.5
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  - pip install nose
  # pip install coverage
  - python -V
  - pip install --upgrade pip setuptools
  # Speed up install by not compiling Cython
  - pip install --install-option="--no-cython-compile" Cython
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
  - popd

script:
  - ./tools/travis-test.sh
