# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 3.3
matrix:
  include:
    - python: 3.3
      env: USE_DEBUG=1
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  - pip install nose
  # pip install coverage
  - python -V
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
  - popd

script:
  - ./tools/travis-test.sh
