# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
group: travis_latest
os: linux
dist: bionic

# Travis allows these packages, additions can be requested
#   https://github.com/travis-ci/apt-package-safelist
addons:
  apt:
    packages: &common_packages
      - gfortran
      - libgfortran5
      - libgfortran3
      - libatlas-base-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

cache:
  directories:
    - $HOME/.cache/pip

stages:
    # Do the style check and a single test job, don't proceed if it fails
    - name: Initial tests

jobs:
  include:
    # Do all python versions without environment variables set
    - stage: Initial tests
      python: 3.9-dev



before_install:
  - ./tools/travis-before-install.sh

script:
  - ./tools/travis-test.sh
