# To enable this workflow on a fork, comment out:
#
# if: github.repository == 'numpy/numpy'

name: CircleCI artifact redirector

on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    if: "github.repository == 'numpy/numpy' && !contains(github.event.head_commit.message, '[circle skip]') && !contains(github.event.head_commit.message, '[skip circle]')  && github.event.context == 'ci/circleci: build'"
    name: Run CircleCI artifacts redirector
    # if: github.repository == 'numpy/numpy'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@bcd0879bbcfd8e15b24dc4069c7a43ccd15c03cc # master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/doc/build/html/index.html
          circleci-jobs: build
