name: CircleCI artifact redirector

on: [status]

permissions: read-all

jobs:
  get_commit_tags:
    name: Get commit tags
    runs-on: ubuntu-latest
    # To enable this workflow on a fork, comment out:
    if: "github.repository == 'numpy/numpy'"
    outputs:
      message: ${{ steps.commit_message.outputs.message }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get commit message
        id: commit_message
        run: |
          set -xe
          COMMIT_TAGS=$(git log --format=%B -n 1 | grep -o '\[[^]]*\]' | tr '\n' ' ' | xargs || true)
          echo "message=$COMMIT_TAGS" >> $GITHUB_OUTPUT
          echo github.ref ${{ github.ref }}
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    needs: get_commit_tags
    if: >-
      !contains(needs.get_commit_tags.outputs.message, '[circle skip]') &&
      !contains(needs.get_commit_tags.outputs.message, '[skip circle]') &&
      github.event.context == 'ci/circleci: build'
    name: Run CircleCI artifacts redirector
    permissions:
      statuses: write
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@4e13a10d89177f4bfc8007a7064bdbeda848d8d1 # master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLE_TOKEN }}
          artifact-path: 0/doc/build/html/index.html
          circleci-jobs: build
