on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build gitpod docker image
    runs-on: ubuntu-latest
    if: github.repository_owner == 'numpy'
    steps:
      - uses: actions/checkout@v2

      # TODO: Setup secrets with docker hub credentials
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./tools/gitpod/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

          # TODO: Update push to true and tags
          push: false
          tags: ${{ github.repository_owner }}/numpy-gitpod:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
