name: Test Meson build (Linux)

on:
  push:
    branches:
      - main
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.11
  NPY_USE_BLAS_ILP64: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  meson_devpy:
    name: meson ${{ matrix.os }}/$${ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ] # macos-latest ]
        python_version: [ '3.10' ]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        pip install -r build_requirements.txt
    - name: Install pkg-config, OpenBLAS (windows)
      if: ${{ startswith( matrix.os, 'windows') }}
      run: |
        choco install pkg-config --no-progress
        target=$(python tools/openblas_support.py)
        # This is the 64-bit interface version
        # If you unset NPY_USE_BLAS_ILP64, use "32" here
        echo "PKG_CONFIG_PATH=$target/64/lib/pkgconfig" >> $GITHUB_ENV
        # This will be prepended to the directives in pkgconfig.pc
        echo "PKG_CONFIG_SYSROOT_DIR=$target" >> $GITHUB_ENV

    - name: Setup OpenBLAS (posix)
      if: ${{ ! startswith( matrix.os, 'windows') }}
      run: |
        target=$(python tools/openblas_support.py)
        echo "PKG_CONFIG_PATH=$target/usr/local/lib/pkgconfig" >> $GITHUB_ENV
        # This will be prepended to the directives in pkgconfig.pc
        echo "PKG_CONFIG_SYSROOT_DIR=$target" >> $GITHUB_ENV

    - name: Build
      # shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
      env:
        TERM: xterm-256color
      run:
        python -m dev.py build -- --werror
    - name: Check build-internal dependencies
      run:
        ninja -C build -t missingdeps
    - name: Check installed test and stub files
      run:
        python tools/check_installed_files.py $(find ./build-install -path '*/site-packages/numpy')
    - name: Test
      env:
        TERM: xterm-256color
      run: |
        python -m pip install -r test_requirements.txt
        python dev.py test
    - name: Show runtime
      run: |
        python -m pip install threadpoolctl
        python tools/openblas_support.py --check_version
        python -c "import numpy as np; np.show_runtime()"
