name: Test Meson build (Linux)

on:
  push:
    branches:
      - main
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.11

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  meson_devpy:
    name: meson ${{ matrix.os }}/$${ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: [ '3.10' ]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        pip install -r build_requirements.txt
    - name: Install OpenBLAS
      run: |
        target=$(python tools/openblas_support.py)
        mkdir openblas
        cp -r $target/* openblas/
        echo "OPENBLAS=$target" >> $GITHUB_ENV
    - name: Build
      shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
      env:
        TERM: xterm-256color
      run:
        python -m dev.py build -- --werror
    - name: Check build-internal dependencies
      run:
        ninja -C build -t missingdeps
    - name: Check installed test and stub files
      run:
        python tools/check_installed_files.py $(find ./build-install -path '*/site-packages/numpy')
    - name: Test
      env:
        TERM: xterm-256color
      run: |
        python -m pip install pytest hypothesis typing_extensions
        python dev.py test
    - name: Show runtime
      run: |
        python -m pip install threadpoolctl
        python tools/openblas_support.py --check_version
        python -c "import numpy as np; np.show_runtime()"
